apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      derivedFields:
        - name: trace_id
          datasourceUid: tempo
          matcherRegex: '"trace_id":"(\w+)"'
          url: '$${__value.raw}'
          urlDisplayLabel: Ver traza en Tempo

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: true
        filterBySpanID: false
        spanStartTimeShift: -1m
        spanEndTimeShift: 1m
      tracesToMetrics:
        datasourceUid: prometheus
        spanStartTimeShift: -1m
        spanEndTimeShift: 1m
        tags:
          - key: service.name
            value: service
        queries:
          - name: Solicitudes por segundo
            query: sum(rate(demo_http_requests_total{$$__tags}[1m]))
          - name: Latencia p95
            query: histogram_quantile(0.95, sum by (le) (rate(demo_http_request_duration_seconds_bucket{$$__tags}[5m])))
